spring:
  datasource: 
      driverClassName: org.h2.Driver
      url: "jdbc:h2:file:./mmmn-persistence/target/h2db-dev/db;INIT=CREATE SCHEMA IF NOT EXISTS keycloak"
      username: erime
      password: erime
  liquibase:
      changeLog: classpath:/liquibase/master.xml
      contexts: dev 