spring:
  application:
    name: mmmn
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hbm2ddl.auto: none
  liquibase.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://to-have-the-jwt-decoder
         
server.servlet.context-path: ""

application:
  external-url: http://mmmn
  keycloak: 
    url: http://keycloak
    login: login
    password: password
  ioda:
    url: https://anruopendata.opendatasoft.com/api/v2
    login:
    password:

springdoc:
  writer-with-order-by-keys: true