spring:
  liquibase:
    changeLog: classpath:/liquibase/master.xml
    contexts: k8s
  datasource: 
      driverClassName: org.postgresql.Driver
      url: "jdbc:mongodb://localhost:27017/mongodb"
      username: test
      password: test
